# configs/config.prod.yaml
server:
  port: "8080"
  read_timeout: "60s"
  write_timeout: "60s"

upload:
  max_file_size: 104857600  # 100MB in bytes
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "application/pdf"
    - "text/plain"
    - "application/msword"
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
  storage_path: "/app/storage"
  #chunk_size: 2097152  # 2MB in bytes

auth:
  jwt_secret: "${JWT_SECRET}"  # Must be set via environment variable
  token_expiration: "12h"

rate_limit:
  requests_per_minute: 120
